from datetime import datetime
from sqlalchemy import String, Integer, Numeric, DateTime, Text, Boolean, ForeignKey, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from .db import Base
class User(Base):
    __tablename__="users"
    id: Mapped[int]=mapped_column(primary_key=True)
    username: Mapped[str]=mapped_column(String(120),unique=True,index=True)
    password_hash: Mapped[str]=mapped_column(String(255))
    role: Mapped[str]=mapped_column(String(30),default="operator")
class Job(Base):
    __tablename__="jobs"
    id: Mapped[int]=mapped_column(primary_key=True)
    filename: Mapped[str]=mapped_column(String(255))
    stored_path: Mapped[str]=mapped_column(Text)
    status: Mapped[str]=mapped_column(String(30),default="pending")
    total: Mapped[int]=mapped_column(Integer,default=0)
    processed: Mapped[int]=mapped_column(Integer,default=0)
    valid: Mapped[int]=mapped_column(Integer,default=0)
    duplicates: Mapped[int]=mapped_column(Integer,default=0)
    errors: Mapped[int]=mapped_column(Integer,default=0)
    message: Mapped[str|None]=mapped_column(Text,nullable=True)
    created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Invoice(Base):
    __tablename__="invoices"
    id: Mapped[int]=mapped_column(primary_key=True)
    uuid: Mapped[str]=mapped_column(String(50),unique=True,index=True)
    sha256: Mapped[str]=mapped_column(String(64),index=True)
    source_file: Mapped[str]=mapped_column(Text)
    version: Mapped[str|None]=mapped_column(String(10))
    serie: Mapped[str|None]=mapped_column(String(60))
    folio: Mapped[str|None]=mapped_column(String(60))
    issue_date: Mapped[str|None]=mapped_column(String(40))
    stamp_date: Mapped[str|None]=mapped_column(String(40))
    voucher_type: Mapped[str|None]=mapped_column(String(5))
    issuer_rfc: Mapped[str|None]=mapped_column(String(20),index=True)
    issuer_name: Mapped[str|None]=mapped_column(Text)
    issuer_regime: Mapped[str|None]=mapped_column(String(10))
    receiver_rfc: Mapped[str|None]=mapped_column(String(20),index=True)
    receiver_name: Mapped[str|None]=mapped_column(Text)
    receiver_regime: Mapped[str|None]=mapped_column(String(10))
    receiver_zip: Mapped[str|None]=mapped_column(String(10))
    cfdi_use: Mapped[str|None]=mapped_column(String(10))
    currency: Mapped[str|None]=mapped_column(String(10))
    exchange_rate: Mapped[str|None]=mapped_column(String(30))
    subtotal: Mapped[float|None]=mapped_column(Numeric(20,6))
    discount: Mapped[float|None]=mapped_column(Numeric(20,6))
    total: Mapped[float|None]=mapped_column(Numeric(20,6))
    payment_form: Mapped[str|None]=mapped_column(String(10))
    payment_method: Mapped[str|None]=mapped_column(String(10))
    expedition_place: Mapped[str|None]=mapped_column(String(10))
    export_code: Mapped[str|None]=mapped_column(String(10))
    pac_rfc: Mapped[str|None]=mapped_column(String(20))
class Concept(Base):
    __tablename__="concepts"
    id: Mapped[int]=mapped_column(primary_key=True)
    invoice_id: Mapped[int]=mapped_column(ForeignKey("invoices.id",ondelete="CASCADE"),index=True)
    line_no: Mapped[int]=mapped_column(Integer)
    product_key: Mapped[str|None]=mapped_column(String(20))
    identification: Mapped[str|None]=mapped_column(Text)
    quantity: Mapped[float|None]=mapped_column(Numeric(20,6))
    unit_key: Mapped[str|None]=mapped_column(String(20))
    unit: Mapped[str|None]=mapped_column(Text)
    description: Mapped[str|None]=mapped_column(Text)
    unit_value: Mapped[float|None]=mapped_column(Numeric(20,6))
    amount: Mapped[float|None]=mapped_column(Numeric(20,6))
    discount: Mapped[float|None]=mapped_column(Numeric(20,6))
    tax_object: Mapped[str|None]=mapped_column(String(10))
    vat_base: Mapped[float|None]=mapped_column(Numeric(20,6))
    vat_rate: Mapped[float|None]=mapped_column(Numeric(20,6))
    vat_transferred: Mapped[float|None]=mapped_column(Numeric(20,6))
    vat_withheld: Mapped[float|None]=mapped_column(Numeric(20,6))
    isr_withheld: Mapped[float|None]=mapped_column(Numeric(20,6))
    ieps_transferred: Mapped[float|None]=mapped_column(Numeric(20,6))
    __table_args__=(UniqueConstraint("invoice_id","line_no"),)
